### ISSUE TITLE
Syntax error !

### ISSUE THREAD

**Issue by enbermudas** [mavinoo/laravelBatch#8]
I got this error while updating a table:

`SQLSTATE[42601]: Syntax error: 7 ERROR: error de sintaxis en o cerca de «`»`

im creating an array for each row i want to update like this:

```
private function customer_array($ctm, $id, $status)
  {

    $array = [
      'code' => rtrim($ctm->co_cli),
      'type' => rtrim($ctm->tip_cli),
      'name' => utf8_encode(strtoupper($ctm->cli_des)),
      'rif' => str_replace('-', '', $ctm->rif),
      'email' => utf8_encode(strtolower($ctm->email)),
      'address1' => utf8_encode(strtoupper($ctm->direc1)),
      'address2' => utf8_encode(strtoupper($ctm->dir_ent2)),
      'phones' => $ctm->telefonos,
      'fax' => $ctm->fax,
      'status' => $status,
      'comment' => utf8_encode($ctm->comentario),
      'responsable' => utf8_encode($ctm->respons),
      'taxpayer' => $ctm->contrib,
      'credit' => $ctm->mont_cre,
      'coin' => rtrim($ctm->co_mone),
      'segment' => $ctm->co_seg,
      'company_id' => $id,
      'payment_condition_name' => $ctm->cond_pag,
      'seller_code' => rtrim($ctm->co_ven),
      'zone_name' => $ctm->co_zon,
    ];

    return $array;

  } // customer_array
```

Because of the size of my data (nearly 5k rows) y use chunks to update them like this:

```
$chunk_customers = array_chunk($act_customers_array, 3);
    foreach ($chunk_customers as $chunk) {
      // Tabla que se actualiza
      $table = 'customers';
      // Valores para actualizar
      $value = $chunk;
      // Indice de referencia
      $index = 'code';
      // Actualizacion
      Batch::update($table, $value, $index);
    }
```

But yes... I keep getting this error over and over again. Any ideas ?

Im ussing Laravel 5.6 and PostgreSQL !

Btw, does this works with PostgreSQL?

**Comment by zoransa** [comment]
This is MySQL specific implementation also he use Common/Helpers::mysql_escape that is not safe at all instead it would be much safer to use built-in 

DB::connection()->getPdo()->quote($text);

I have used this for some internal tool and I do not worry much since it is MySQL and it will never be anything else and I deal with numbers and strings that are safe coming from lists or md5 so I know there is no danger in the input so this implementation does the job and I do not have to bother writing my own but it is not universal and most probably not even safe.

**Comment by mavinoo** [comment]
@enbermudas  [Added support for batch support for postgres](https://github.com/mavinoo/laravelBatch/commit/9bec55b20e89680b232cdf79e3f3023977f5dbf8)

**Comment by Seiger** [comment]
It seems you forgot to add this to the release. I just installed your package and am still getting error with PostgreSQL DB
